## Model Training

#### 1.1 Import Data and Required Packages
##### Importing Pandas, Numpy, Matplotlib, Seaborn and Warings Library.

In [38]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
# Modelling
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV
from sklearn.linear_model import RidgeClassifier
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import warnings


#### Import the CSV Data as Pandas DataFrame

In [39]:
df = pd.read_csv('E:\\Bank_cicd\\notebook\\data\\Diabetes_prediction.csv')

In [40]:
df.columns


Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

#### Show Top 5 Records

In [41]:
df.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0    Male  80.0             1              0          former  27.32   
1  Female  35.0             0              0         No_Info  27.32   
2  Female  55.0             1              0           never  27.32   
3    Male  68.0             0              0          former  28.19   
4  Female  26.0             0              0     not_current  21.38   

   HbA1c_level  blood_glucose_level  diabetes  
0          8.2                  140         1  
1          4.5                  158         0  
2          8.8                  220         1  
3          3.5                  100         0  
4          5.8                  155         0

In [42]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'smoking_history',
       'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes'],
      dtype='object')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               17000 non-null  object 
 1   age                  17000 non-null  float64
 2   hypertension         17000 non-null  int64  
 3   heart_disease        17000 non-null  int64  
 4   smoking_history      17000 non-null  object 
 5   bmi                  17000 non-null  float64
 6   HbA1c_level          17000 non-null  float64
 7   blood_glucose_level  17000 non-null  int64  
 8   diabetes             17000 non-null  int64  
dtypes: float64(3), int64(4), object(2)
memory usage: 1.2+ MB


In [44]:
df

gender   age  hypertension  heart_disease smoking_history    bmi  \
0        Male  80.0             1              0          former  27.32   
1      Female  35.0             0              0         No_Info  27.32   
2      Female  55.0             1              0           never  27.32   
3        Male  68.0             0              0          former  28.19   
4      Female  26.0             0              0     not_current  21.38   
...       ...   ...           ...            ...             ...    ...   
16995  Female  39.0             0              0           never  39.69   
16996    Male  68.0             0              0           never  28.56   
16997  Female  39.0             0              0           never  22.44   
16998    Male  26.0             0              0         No_Info  27.32   
16999  Female  73.0             0              0         No_Info  27.32   

       HbA1c_level  blood_glucose_level  diabetes  
0              8.2                  140         1  
1              4.5                  158         0  
2              8.8                  220         1  
3              3.5                  100         0  
4              5.8                  155         0  
...            ...                  ...       ...  
16995          6.1                  200         1  
16996          6.8                  220         1  
16997          4.8                  145         0  
16998          6.5                   80         0  
16999          5.8                  160         1  

[17000 rows x 9 columns]

In [45]:
import pandas as pd


# Assuming your DataFrame is named df

# Get list of numerical columns
numerical_columns = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Get list of categorical columns
categorical_columns = df.select_dtypes(include=['object']).columns.tolist()

# Display the lists
print("Numerical Columns:")
print(numerical_columns)
print("\nCategorical Columns:")
print(categorical_columns)


Numerical Columns:
['age', 'hypertension', 'heart_disease', 'bmi', 'HbA1c_level', 'blood_glucose_level', 'diabetes']

Categorical Columns:
['gender', 'smoking_history']


In [46]:
# Find unique categories in each categorical column
for column in categorical_columns:
    unique_categories = df[column].unique()
    print(f"Unique categories in '{column}':")
    print(unique_categories)
    print()


Unique categories in 'gender':
['Male' 'Female' 'Other']

Unique categories in 'smoking_history':
['former' 'No_Info' 'never' 'not_current' 'current' 'ever']



In [48]:
X = df.drop(columns=['diabetes'],axis=1)   # iv  


In [49]:
y = df['diabetes']

In [50]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [52]:
numerical_cols

Index(['age', 'hypertension', 'heart_disease', 'bmi', 'HbA1c_level',
       'blood_glucose_level'],
      dtype='object')

In [53]:
categorical_cols

Index(['gender', 'smoking_history'], dtype='object')

In [54]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [55]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [56]:
X = preprocessor.fit_transform(X)

In [57]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((13600, 15), (3400, 15))

#### here we do label encoding WRT to dependent variable 

In [58]:
from sklearn.preprocessing import LabelEncoder

# Encode target variable y
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_test= label_encoder.transform(y_test)

In [ ]:
# Applying one-hot encoding to the dependent variable (target variable) is not standard practice for binary classification tasks. , if more han 2 we can use it 

# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# # Perform one-hot encoding on encoded target variable
# onehot_encoder = OneHotEncoder(sparse=False)
# y_train_onehot = onehot_encoder.fit_transform(y_train_encoded.reshape(-1, 1))
# y_test_onehot = onehot_encoder.transform(y_test_encoded.reshape(-1, 1))

In [59]:
def evaluate_model(true, predicted):
    # Calculate classification accuracy
    accuracy = accuracy_score(true, predicted)
    
    # Calculate precision, recall, and F1-score for each class
    precision = precision_score(true, predicted, average='macro')
    recall = recall_score(true, predicted, average='macro')
    f1 = f1_score(true, predicted, average='macro')
    
    # Calculate confusion matrix
    cm = confusion_matrix(true, predicted)
    
    return accuracy, precision, recall, f1, cm 

In [60]:
models = {
    "LogisticRegression":  LogisticRegression(),
    "SVC": SVC(),
    "RidgeClassifier": RidgeClassifier(),
    "KNeighborsClassifier":  KNeighborsClassifier(),
    "DecisionTreeClassifier": DecisionTreeClassifier(),
    "XGBClassifier": XGBClassifier(), 
    "CatBoostClassifier": CatBoostClassifier(verbose=False),
    "AdaBoostClassifier": AdaBoostClassifier()
}
model_list = []
accuracy_list =[]
precision_list = []
recall_list = []
f1_list = []

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)
    
    # Evaluate Train and Test dataset
    model_train_accuracy, model_train_precision, model_train_recall, model_train_f1, model_train_cm = evaluate_model(y_train, y_train_pred)

    model_test_accuracy, model_test_precision, model_test_recall, model_test_f1, model_test_cm = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Accuracy: {:.4f}".format(model_train_accuracy))
    print("- Precision: {:.4f}".format(model_train_precision))
    print("- Recall: {:.4f}".format(model_train_recall))
    print("- F1 Score: {:.4f}".format(model_train_f1))
    print("- Confusion Matrix:\n", model_train_cm)

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Accuracy: {:.4f}".format(model_test_accuracy))
    print("- Precision: {:.4f}".format(model_test_precision))
    print("- Recall: {:.4f}".format(model_test_recall))
    print("- F1 Score: {:.4f}".format(model_test_f1))
    print("- Confusion Matrix:\n", model_test_cm)

    accuracy_list.append(model_test_accuracy)

    print('='*35)
    print('\n')

LogisticRegression
Model performance for Training set
- Accuracy: 0.8868
- Precision: 0.8868
- Recall: 0.8868
- F1 Score: 0.8868
- Confusion Matrix:
 [[6058  744]
 [ 796 6002]]
----------------------------------
Model performance for Test set
- Accuracy: 0.8844
- Precision: 0.8844
- Recall: 0.8844
- F1 Score: 0.8844
- Confusion Matrix:
 [[1500  198]
 [ 195 1507]]


SVC
Model performance for Training set
- Accuracy: 0.9002
- Precision: 0.9003
- Recall: 0.9002
- F1 Score: 0.9002
- Confusion Matrix:
 [[6081  721]
 [ 636 6162]]
----------------------------------
Model performance for Test set
- Accuracy: 0.8912
- Precision: 0.8912
- Recall: 0.8912
- F1 Score: 0.8912
- Confusion Matrix:
 [[1502  196]
 [ 174 1528]]


RidgeClassifier
Model performance for Training set
- Accuracy: 0.8875
- Precision: 0.8877
- Recall: 0.8875
- F1 Score: 0.8875
- Confusion Matrix:
 [[6111  691]
 [ 839 5959]]
----------------------------------
Model performance for Test set
- Accuracy: 0.8797
- Precision: 0.8799


In [61]:

pd.DataFrame(list(zip(model_list, accuracy_list)), columns=['Model Name', 'accuracy']).sort_values(by=["accuracy"],ascending=False)

Model Name  accuracy
6      CatBoostClassifier  0.910882
5           XGBClassifier  0.910000
7      AdaBoostClassifier  0.908529
1                     SVC  0.891176
0      LogisticRegression  0.884412
4  DecisionTreeClassifier  0.881765
2         RidgeClassifier  0.879706
3    KNeighborsClassifier  0.871176

In [62]:
lin_model = CatBoostClassifier()
lin_model = lin_model.fit(X_train, y_train)
y_pred = lin_model.predict(X_test)
score = accuracy_score(y_test, y_pred)*100
print(f"accuracy score is {score}")
# print(f"Accuracy of the model is "{score})

Learning rate set to 0.031402
0:	learn: 0.6267096	total: 12.3ms	remaining: 12.2s
1:	learn: 0.5683548	total: 21.9ms	remaining: 10.9s
2:	learn: 0.5190264	total: 31.5ms	remaining: 10.5s
3:	learn: 0.4766775	total: 41.2ms	remaining: 10.3s
4:	learn: 0.4403478	total: 51.8ms	remaining: 10.3s
5:	learn: 0.4104978	total: 61.6ms	remaining: 10.2s
6:	learn: 0.3831053	total: 71.1ms	remaining: 10.1s
7:	learn: 0.3628041	total: 80.7ms	remaining: 10s
8:	learn: 0.3418597	total: 90.3ms	remaining: 9.94s
9:	learn: 0.3241547	total: 100ms	remaining: 9.91s
10:	learn: 0.3119069	total: 110ms	remaining: 9.9s
11:	learn: 0.2998197	total: 121ms	remaining: 9.95s
12:	learn: 0.2877002	total: 131ms	remaining: 9.91s
13:	learn: 0.2786520	total: 141ms	remaining: 9.92s
14:	learn: 0.2706813	total: 157ms	remaining: 10.3s
15:	learn: 0.2638821	total: 167ms	remaining: 10.3s
16:	learn: 0.2575017	total: 176ms	remaining: 10.2s
17:	learn: 0.2523448	total: 186ms	remaining: 10.2s
18:	learn: 0.2479573	total: 196ms	remaining: 10.1s
19:	l

In [63]:
pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_pred,'Difference':y_test-y_pred})
pred_df

Actual Value  Predicted Value  Difference
0                1                1           0
1                1                1           0
2                1                1           0
3                1                1           0
4                1                1           0
...            ...              ...         ...
3395             0                0           0
3396             1                1           0
3397             1                1           0
3398             1                1           0
3399             0                0           0

[3400 rows x 3 columns]

In [104]:
# import os

# # Define the path where you want to save the file
# folder_path = "E:/BANK_CICD/notebook/data"
# file_name = "bank_marketing_deposit_prediction.csv"

# # Concatenate the folder path and file name
# file_path = os.path.join(folder_path, file_name)

# # Save the DataFrame to CSV without the index
# df.to_csv(file_path, index=False)

# print(f"File saved successfully at: {file_path}")


File saved successfully at: E:/BANK_CICD/notebook/data\bank_marketing_deposit_prediction.csv
